---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/math6746/public_html/
    - /bin/cp -f /home2/math6746/casa42-repo/index.html $DEPLOYPATH
    - /bin/cp -f /home2/math6746/casa42-repo/style.css $DEPLOYPATH
    - /bin/cp -f /home2/math6746/casa42-repo/script.js $DEPLOYPATH
    - /bin/mkdir -p ${DEPLOYPATH}assets
    - /bin/cp -rf /home2/math6746/casa42-repo/assets/. ${DEPLOYPATH}assets/
