name: Deploy para HostGator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -p 2222 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Enviar arquivos via SFTP
        run: |
          sftp -i ~/.ssh/deploy_key -P 2222 -o StrictHostKeyChecking=no -b - ${{ secrets.FTP_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd public_html
          put index.html
          put favicon.png
          put foto_igreja.PNG
          put pastor.PNG
          mkdir assets
          cd assets
          put assets/geracao_foto1.png
          put assets/geracao_foto2.png
          put assets/geracao_foto3.gif
          put assets/geracao_hero.gif
          put assets/geracao_on.gif
          bye
          EOF
